# Cognito - Client
CognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:provider.environment.COGNITO_USER_POOL_CLIENT}
    UserPoolId:
      Ref: CognitoUserPool
